# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'proxybuilder/proxybuild.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(690, 676)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setTabShape(QtGui.QTabWidget.Triangular)
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setStyleSheet(_fromUtf8(""))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.Sim_tab = QtGui.QWidget()
        self.Sim_tab.setObjectName(_fromUtf8("Sim_tab"))
        self.output_dir_lbl = QtGui.QLabel(self.Sim_tab)
        self.output_dir_lbl.setGeometry(QtCore.QRect(150, 80, 501, 31))
        self.output_dir_lbl.setObjectName(_fromUtf8("output_dir_lbl"))
        self.filename_lbl = QtGui.QLabel(self.Sim_tab)
        self.filename_lbl.setGeometry(QtCore.QRect(160, 20, 491, 21))
        self.filename_lbl.setObjectName(_fromUtf8("filename_lbl"))
        self.open_file_btn = QtGui.QPushButton(self.Sim_tab)
        self.open_file_btn.setGeometry(QtCore.QRect(20, 20, 114, 21))
        self.open_file_btn.setObjectName(_fromUtf8("open_file_btn"))
        self.scan_file_btn = QtGui.QPushButton(self.Sim_tab)
        self.scan_file_btn.setGeometry(QtCore.QRect(440, 40, 221, 32))
        self.scan_file_btn.setObjectName(_fromUtf8("scan_file_btn"))
        self.set_output_dir_btn = QtGui.QPushButton(self.Sim_tab)
        self.set_output_dir_btn.setGeometry(QtCore.QRect(20, 80, 114, 32))
        self.set_output_dir_btn.setObjectName(_fromUtf8("set_output_dir_btn"))
        self.build_btn = QtGui.QPushButton(self.Sim_tab)
        self.build_btn.setGeometry(QtCore.QRect(-10, 160, 681, 51))
        self.build_btn.setObjectName(_fromUtf8("build_btn"))
        self.progress_bar = QtGui.QProgressBar(self.Sim_tab)
        self.progress_bar.setGeometry(QtCore.QRect(0, 210, 661, 23))
        self.progress_bar.setProperty("value", 24)
        self.progress_bar.setObjectName(_fromUtf8("progress_bar"))
        self.ffmpeg_opts_edit = QtGui.QLineEdit(self.Sim_tab)
        self.ffmpeg_opts_edit.setGeometry(QtCore.QRect(130, 130, 521, 21))
        self.ffmpeg_opts_edit.setObjectName(_fromUtf8("ffmpeg_opts_edit"))
        self.ffmpeg_opts_lbl = QtGui.QLabel(self.Sim_tab)
        self.ffmpeg_opts_lbl.setGeometry(QtCore.QRect(20, 120, 101, 31))
        self.ffmpeg_opts_lbl.setObjectName(_fromUtf8("ffmpeg_opts_lbl"))
        self.text_browser = QtGui.QPlainTextEdit(self.Sim_tab)
        self.text_browser.setGeometry(QtCore.QRect(0, 240, 661, 291))
        self.text_browser.setObjectName(_fromUtf8("text_browser"))
        self.tabWidget.addTab(self.Sim_tab, _fromUtf8(""))
        self.adv_tab = QtGui.QWidget()
        self.adv_tab.setObjectName(_fromUtf8("adv_tab"))
        self.ffmpeg_loc_edit = QtGui.QLineEdit(self.adv_tab)
        self.ffmpeg_loc_edit.setGeometry(QtCore.QRect(180, 50, 471, 21))
        self.ffmpeg_loc_edit.setObjectName(_fromUtf8("ffmpeg_loc_edit"))
        self.vbr_edit = QtGui.QLineEdit(self.adv_tab)
        self.vbr_edit.setGeometry(QtCore.QRect(180, 250, 113, 21))
        self.vbr_edit.setObjectName(_fromUtf8("vbr_edit"))
        self.ffmpeg_loc_lbl = QtGui.QLabel(self.adv_tab)
        self.ffmpeg_loc_lbl.setGeometry(QtCore.QRect(30, 50, 111, 21))
        self.ffmpeg_loc_lbl.setObjectName(_fromUtf8("ffmpeg_loc_lbl"))
        self.ffprobe_loc_lbl = QtGui.QLabel(self.adv_tab)
        self.ffprobe_loc_lbl.setGeometry(QtCore.QRect(30, 80, 111, 21))
        self.ffprobe_loc_lbl.setObjectName(_fromUtf8("ffprobe_loc_lbl"))
        self.crf_lbl = QtGui.QLabel(self.adv_tab)
        self.crf_lbl.setGeometry(QtCore.QRect(400, 300, 71, 31))
        self.crf_lbl.setObjectName(_fromUtf8("crf_lbl"))
        self.abr_lbl = QtGui.QLabel(self.adv_tab)
        self.abr_lbl.setGeometry(QtCore.QRect(30, 280, 111, 21))
        self.abr_lbl.setObjectName(_fromUtf8("abr_lbl"))
        self.ffprobe_loc_edit = QtGui.QLineEdit(self.adv_tab)
        self.ffprobe_loc_edit.setGeometry(QtCore.QRect(180, 80, 471, 21))
        self.ffprobe_loc_edit.setObjectName(_fromUtf8("ffprobe_loc_edit"))
        self.vbr_lbl = QtGui.QLabel(self.adv_tab)
        self.vbr_lbl.setGeometry(QtCore.QRect(30, 250, 111, 21))
        self.vbr_lbl.setObjectName(_fromUtf8("vbr_lbl"))
        self.abr_edit = QtGui.QLineEdit(self.adv_tab)
        self.abr_edit.setGeometry(QtCore.QRect(180, 280, 113, 21))
        self.abr_edit.setObjectName(_fromUtf8("abr_edit"))
        self.crf_slider = QtGui.QSlider(self.adv_tab)
        self.crf_slider.setGeometry(QtCore.QRect(400, 380, 241, 22))
        self.crf_slider.setMaximum(51)
        self.crf_slider.setOrientation(QtCore.Qt.Horizontal)
        self.crf_slider.setObjectName(_fromUtf8("crf_slider"))
        self.screen_size_lbl = QtGui.QLabel(self.adv_tab)
        self.screen_size_lbl.setGeometry(QtCore.QRect(30, 150, 111, 21))
        self.screen_size_lbl.setObjectName(_fromUtf8("screen_size_lbl"))
        self.crf_out_lcd = QtGui.QLCDNumber(self.adv_tab)
        self.crf_out_lcd.setGeometry(QtCore.QRect(510, 300, 111, 61))
        self.crf_out_lcd.setObjectName(_fromUtf8("crf_out_lcd"))
        self.screen_size_opts = QtGui.QComboBox(self.adv_tab)
        self.screen_size_opts.setGeometry(QtCore.QRect(180, 150, 231, 26))
        self.screen_size_opts.setObjectName(_fromUtf8("screen_size_opts"))
        self.tabWidget.addTab(self.adv_tab, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 690, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionNew = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/open-file-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew.setIcon(icon)
        self.actionNew.setObjectName(_fromUtf8("actionNew"))
        self.actionScan = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/scan-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionScan.setIcon(icon1)
        self.actionScan.setObjectName(_fromUtf8("actionScan"))
        self.actionBuild = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/build-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBuild.setIcon(icon2)
        self.actionBuild.setObjectName(_fromUtf8("actionBuild"))
        self.actionQuit = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/quit-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon3)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionSettings = QtGui.QAction(MainWindow)
        self.actionSettings.setObjectName(_fromUtf8("actionSettings"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionSet_Proxy_Folder = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Folder-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSet_Proxy_Folder.setIcon(icon4)
        self.actionSet_Proxy_Folder.setObjectName(_fromUtf8("actionSet_Proxy_Folder"))
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionScan)
        self.menuFile.addAction(self.actionBuild)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuEdit.addAction(self.actionSet_Proxy_Folder)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionNew)
        self.toolBar.addAction(self.actionScan)
        self.toolBar.addAction(self.actionSet_Proxy_Folder)
        self.toolBar.addAction(self.actionBuild)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionQuit)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.crf_slider, QtCore.SIGNAL(_fromUtf8("sliderMoved(int)")), self.crf_out_lcd.display)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.msgbx = QtGui.QMessageBox()

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Proxy Builder", None))
        self.output_dir_lbl.setText(_translate("MainWindow", "TextLabel", None))
        self.filename_lbl.setText(_translate("MainWindow", "TextLabel", None))
        self.open_file_btn.setText(_translate("MainWindow", "Browse", None))
        self.scan_file_btn.setText(_translate("MainWindow", "Scan file", None))
        self.set_output_dir_btn.setText(_translate("MainWindow", "Proxy Folder", None))
        self.build_btn.setText(_translate("MainWindow", "Build Proxy", None))
        self.ffmpeg_opts_lbl.setText(_translate("MainWindow", "FFMpeg options", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Sim_tab), _translate("MainWindow", "Quick", None))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.Sim_tab), _translate("MainWindow", "Quick settings to build a proxy file", None))
        self.ffmpeg_loc_lbl.setText(_translate("MainWindow", "FFMpeg location", None))
        self.ffprobe_loc_lbl.setText(_translate("MainWindow", "FFProbe location", None))
        self.crf_lbl.setText(_translate("MainWindow", "CRF Value", None))
        self.abr_lbl.setText(_translate("MainWindow", "Audio Bitrate", None))
        self.vbr_lbl.setText(_translate("MainWindow", "Video Bitrate", None))
        self.screen_size_lbl.setText(_translate("MainWindow", "Screen size", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.adv_tab), _translate("MainWindow", "Advanced", None))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.adv_tab), _translate("MainWindow", "More settings to fine-tune the quality", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.actionNew.setText(_translate("MainWindow", "New", None))
        self.actionNew.setToolTip(_translate("MainWindow", "Open a new file", None))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.actionScan.setText(_translate("MainWindow", "Scan", None))
        self.actionScan.setToolTip(_translate("MainWindow", "Scan your selected file", None))
        self.actionScan.setShortcut(_translate("MainWindow", "Ctrl+Shift+D", None))
        self.actionBuild.setText(_translate("MainWindow", "Build", None))
        self.actionBuild.setToolTip(_translate("MainWindow", "Build a proxy file", None))
        self.actionBuild.setShortcut(_translate("MainWindow", "Ctrl+Shift+B", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionSettings.setText(_translate("MainWindow", "Settings", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.actionSet_Proxy_Folder.setText(_translate("MainWindow", "Proxy Folder", None))
        self.actionSet_Proxy_Folder.setToolTip(_translate("MainWindow", "Choose a folder to save the proxy file", None))
        self.actionSet_Proxy_Folder.setShortcut(_translate("MainWindow", "Ctrl+Shift+S", None))

import icons_rc
